### ISSUE TITLE
[CLI] AttributeError when logging retryable connection errors

### ISSUE THREAD

**Issue by gwenzek** [wandb/client#2067]
**Description**
On connection errors I get the following stack trace:

```
Traceback (most recent call last):
  File "/private/home/guw/.conda/envs/bt_dev/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/private/home/guw/.conda/envs/bt_dev/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/private/home/guw/.conda/envs/bt_dev/lib/python3.8/site-packages/wandb/sdk/internal/file_stream.py", line 261, in _thread_body
    util.request_with_retry(
  File "/private/home/guw/.conda/envs/bt_dev/lib/python3.8/site-packages/wandb/util.py", line 766, in request_with_retry
    e.response.content,                                                        
AttributeError: 'NoneType' object has no attribute 'content'   
```

Looking at the code it seems that  the error was just meant to be logged and retried, but here we get a crash instead.
The original error was just a `ConnectionResetError: [Errno 104] Connection reset by peer  ` (wrapped several times).

I think this has been introduced in #1586 see my comment: https://github.com/wandb/client/pull/1586/files#r612291024

**Wandb features**
I'm using Wandb 0.10.25 with Fairseq and  `WANDB_START_METHOD="thread"`

**How to reproduce**
1. Not sure how to reproduce. Maybe it should be reproduce in a test case, by mocking the request library to raise an exception without response.

**Environment**
- OS: Linux
- Environment: Slurm Cluster 
- Python Version: 3.8.5
- Wandb: 0.10.25
- requests: 2.24.0

**Comment by vanpelt** [comment]
Thanks for this report.  We're looking into a fix ASAP.

**Comment by raubitsj** [comment]
Thanks for the report, this is fixed in 0.10.26.

As you found, it was a bug introduced in 0.10.24 and we are improving our testing processes to make sure we don't introduce a problem in this part of the code again.

If you have any runs impacted by the bug that ran to completion but did not sync all the data, you can use the `wandb sync` command to complete the syncing of any files or metrics which were impacted by this network handling bug.

**Comment by gwenzek** [comment]
Thanks for the quick fix!
