### ISSUE TITLE
[CLI] wandb.restore() does not work for sweep runs v0.11.2 

### ISSUE THREAD

**Issue by ivanovitchm** [wandb/client#2510]
**Description**
It is not possible to restore a model (or any other file) using version 0.11.2 when considered "runs" executed in a Sweep: 

wandb.restore('file', run_path="user/project/hash")

This only works if run_path is related to a "run" that was executed without a Sweep.

I had tested the same procedure with version 0.10.17 and it worked. Apparently, it is problem in version 0.11.2.

**Comment by vanpelt** [comment]
@ivanovitchm this is really strange.  Can you share a `run_path` for a run that works in 0.11.2 and one that doesn't?

**Comment by ivanovitchm** [comment]
> @ivanovitchm this is really strange. Can you share a `run_path` for a run that works in 0.11.2 and one that doesn't?

This `run_path`is one come from without sweep: **ivanovitchm/wandb_restore_evaluation/3nsyl2os** it works!!!

On the other hand, this `run_path`come from sweep: **ivanovitchm/wandb_restore_evaluation/01catu9s** it doesn`t work.

**Comment by vanpelt** [comment]
Hey @ivanovitchm are you seeing an error when this happens, or it's just not downloading any file?  Also, what file specifically are you attempting to restore?

**Comment by ivanovitchm** [comment]
I got an error, the log is below.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/wandb/apis/normalize.py in wrapper(*args, **kwargs)
     23         try:
---> 24             return func(*args, **kwargs)
     25         except requests.HTTPError as err:

10 frames
AttributeError: 'Runs' object has no attribute 'append'

During handling of the above exception, another exception occurred:

CommError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/wandb/apis/public.py in load(self, force)
   1005                 # TODO: Older runs don't always have sweeps when sweep_name is set
   1006                 if self.sweep:
-> 1007                     self.sweep.runs.append(self)
   1008 
   1009         self._attrs["summaryMetrics"] = (

CommError: 'Runs' object has no attribute 'append'

**Comment by vanpelt** [comment]
Hey @ivanovitchm I believe I just fixed the bug.  This should go out in the next official release.  If you want to try using it now, you can run:

```
pip install --upgrade git+git://github.com/wandb/client.git@bug/sweep_runs#egg=wandb
```

**Comment by ivanovitchm** [comment]
> Hey @ivanovitchm I believe I just fixed the bug. This should go out in the next official release. If you want to try using it now, you can run:
> 
> ```
> pip install --upgrade git+git://github.com/wandb/client.git@bug/sweep_runs#egg=wandb
> ```

Thanks a lot @vanpelt , I will finish the notebook for my class now :-)
