### ISSUE TITLE
[sweeps] No module named 'wandb.sweeps'

### ISSUE THREAD

**Issue by stefanalgopolis** [wandb/client#2710]
I wanted to run HyperOpt sweeps in wandb, as it is described in your documentation: https://docs.wandb.ai/guides/sweeps/advanced-sweeps/ray-tune

Unfortunately, I'm not able to import wandb.sweeps module:

```
import wandb
from wandb.sweeps.config import tune

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'wandb.sweeps'
```
What may be the reason for that? I'm using the latest version of wandb library

**Comment by alvarobartt** [comment]
Hi @stefanalgopolis, try installing `wandb` as it follows:

```
pip install wandb[sweeps]
```

I think that should work! 🎉

**Comment by stefanalgopolis** [comment]
Hi @alvarobartt , thanks for your reply! I did as you suggested, wandb.sweeps is now possible to import but I received another error, regarding tune method:

```
>>> import wandb
>>> from wandb.sweeps.config import tune
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'tune' from 'wandb.sweeps.config' (/home/user/.cache/pypoetry/virtualenvs/ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/sweeps/config/__init__.py)
```

I've checked content of `wandb/sweeps/config/__init__.py` and there is no tune method to import:
```
# -*- coding: utf-8 -*-
"""Sweep config interface."""
from .cfg import SweepConfig, schema_violations_from_proposed_config
from .schema import fill_validate_schema, fill_parameter, fill_validate_early_terminate

__all__ = [
    "SweepConfig",
    "schema_violations_from_proposed_config",
    "fill_validate_schema",
    "fill_parameter",
    "fill_validate_early_terminate",
]
```

**Comment by alvarobartt** [comment]
You're right @stefanalgopolis, can you try with `pip install wandb[sweeps]==0.10.24`?

**Comment by alvarobartt** [comment]
Anyway, should this be considered a bug @vanpelt? Maybe some more tests should be included so as to properly test this, since AFAIK it hasn't been working for the last couple of releases 😕

**Comment by stefanalgopolis** [comment]
@alvarobartt It works with `pip install wandb[sweeps]==0.10.24` 

Thanks for your help!

**Comment by dannygoldstein** [comment]
Hi @stefanalgopolis, @alvarobartt, we removed ray/tune and hyperopt sweeps in 0.11.1 during a refactor of our sweeps engine due to low usage. We'll update the documentation and examples to reflect this.
