### ISSUE TITLE
[CLI]: SB3 integration broken `ImportError: cannot import name 'WandbCallback' from 'wandb.integration'`

### ISSUE THREAD

**Issue by vwxyzjn** [wandb/client#3426]
### Describe the bug

With `wandb==0.12.11` the SB3 integration no longer works:

```python 
(gym-minigrid-bHG13Wwr-py3.9) ➜  gym-minigrid git:(master) python
Python 3.9.5 (default, Jul 19 2021, 13:27:26) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> wandb.__version__
'0.12.11'
>>> from wandb.integration import WandbCallback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'WandbCallback' from 'wandb.integration' (/home/costa/.cache/pypoetry/virtualenvs/gym-minigrid-bHG13Wwr-py3.9/lib/python3.9/site-packages/wandb/integration/__init__.py)
```

### Environment

WandB version:0.12.11

OS: Linux

Python version: 3.8

Versions of relevant libraries:

**Comment by ramit-wandb** [comment]
Hi @vwxyzjn,

I just tested this on my end, and you would want to call `from wandb.integration.sb3 import WandbCallback`.

This seems to work on v0.12.11 as well.

Thanks,
Ramit

**Comment by vwxyzjn** [comment]
Oh nvm. I mistyped. Thanks @ramit-wandb!
